---
galaxy_info:
  author: Malakhovsky Daniil (@issvvv)
  description: Playbook to setup Opensearch cluster for RedHat OS types.
  license: MIT
  min_ansible_version: '2.7'
  galaxy_tags: ['opensearch']

  platforms:
    - name: EL
      versions: ['7', '8', '9']
    - name: Debian
      versions: ['bullseye', 'bookworm']

collections:
  - ansible.posix
