---
#########################################################################################
### REDIS ###############################################################################

defaults_redis_server_service_port: 6379
defaults_redis_server_sentinel_port: 26379

defaults_redis_server_tmp_dir: "/tmp/redis"
defaults_redis_server_instance_dir: "{{ redis_server_root_dir }}/redis-{{ redis_server_version }}"
defaults_redis_server_data_dir: "{{ redis_server_root_dir }}/data"
defaults_redis_server_bin_dir: "{{ redis_server_root_dir }}/bin"
defaults_redis_server_log_dir: "{{ redis_server_root_dir }}/log"

defaults_redis_server_directories:
  - "{{ redis_server_root_dir }}"
  - "{{ defaults_redis_server_data_dir }}"
  - "{{ defaults_redis_server_bin_dir }}"
  - "{{ defaults_redis_server_log_dir }}"
  - "{{ defaults_redis_server_tmp_dir }}"

defaults_redis_server_build_dependencies_packages:
  - gcc
  - make
  - tcl

#########################################################################################
### FIREWALLD ###########################################################################

defaults_redis_server_firewalld_ports:
  - "{{ defaults_redis_server_service_port }}/tcp"
  - "{{ defaults_redis_server_service_port | int + 10000 }}/tcp"
  - "{{ defaults_redis_server_sentinel_port }}/tcp"
