---
- name: Check firewalld status
  ansible.builtin.set_fact:
    opensearch_firewalld_enabled: true
  when:
    - ansible_facts.services["firewalld.service"] is defined
    - ansible_facts.services["firewalld.service"].state == "running"

- name: Be sure ports traffic permited
  become: true
  ansible.posix.firewalld:
    port: "{{ item }}"
    zone: public
    permanent: true
    state: enabled
  loop: "{{ opensearch_firewalld_ports }}"
  changed_when: true
  when: opensearch_firewalld_enabled | bool
