---
- name: Install | Update Opensearch service version
  block:
    - name: Pull Opensearch archive
      become: true
      become_user: "{{ opensearch_service_user }}"
      ansible.builtin.get_url:
        url: "{{ opensearch_service_download_url }}"
        dest: "{{ opensearch_server_tmp_dir }}"
        mode: '0644'
      when:
        - not opensearch_service_is_installed or
          opensearch_service_version not in opensearch_service_current_version

    - name: Stop current Opensearch service
      become: true
      ansible.builtin.systemd_service:
        name: opensearch.service
        state: stopped
      when:
        - opensearch_service_is_installed and
          opensearch_service_version not in opensearch_service_current_version

    - name: Delete existing Opensearch instance if exists
      become: true
      ansible.builtin.file:
        path: "{{ opensearch_server_instance_dir }}/{{ item }}"
        state: absent
      with_fileglob: "{{ opensearch_server_instance_dir + '/*' }}"
      when:
        - opensearch_service_is_installed and
          opensearch_service_version not in opensearch_service_current_version

    - name: Unarchive pulled Opensearch archive
      become: true
      become_user: "{{ opensearch_service_user }}"
      ansible.builtin.unarchive:
        src: "{{ opensearch_server_tmp_dir }}/{{ opensearch_service_package_name }}"
        dest: "{{ opensearch_server_root_dir }}"
        remote_src: true
      when:
        - not opensearch_service_is_installed or
          opensearch_service_version not in opensearch_service_current_version
      notify: restart_opensearch_service

- name: Config | Template Opensearch service config
  become: true
  ansible.builtin.template:
    src: "config/opensearch.yml.j2"
    dest: "{{ opensearch_server_instance_dir }}/opensearch.yml"
    owner: "{{ opensearch_service_user }}"
    group: "{{ opensearch_service_group }}"
    mode: '0600'
  notify: restart_opensearch_service

- name: Systemd | Template Opensearch systemd unit file
  become: true
  ansible.builtin.template:
    src: "opensearch.service.j2"
    dest: "/etc/systemd/system/opensearch.service"
    owner: root
    group: root
    mode: '0644'
  notify: restart_opensearch_service

- name: Logrotate | Configure Opensearch logrotate config
  become: true
  ansible.builtin.template:
    src: "logrotate/opensearch.j2"
    dest: "/etc/logrotate.d/opensearch"
    owner: root
    group: root
    mode: '0644'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
