---
- name: Set vm.max_map_count
  become: true
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '{{ opensearch_sysctl_vm_max_map_count }}'
    state: present
    reload: true

- name: Set open files limit
  become: true
  ansible.posix.sysctl:
    name: "fs.file-max"
    value: "65536"
    state: present
