---
# Redis version
redis_server_version: "8.6.1"
redis_server_package_name: "redis-{{ redis_server_version }}.tar.gz"
redis_server_download_url: "https://download.redis.io/releases/{{ redis_server_package_name }}"

# Redis installation type:  standalone — single-node server; replication — HA Redis with replication; cluster — sharded Redis cluster.
redis_server_instance_type: "standalone"
redis_server_protected_mode: true

# You need it only if redis_server_instance_type is set to 'replication'
redis_server_sentinel_enabled: false

# Password protection
redis_server_password: ""

redis_server_root_dir: "/opt/redis"

redis_server_service_user: "redis"
redis_server_service_group: "redis"
