---

- name: Check if minikube exists
  ansible.builtin.stat:
    path: "{{ minikube_path }}"
  register: minikube_existion

- name: Install minikube
  ansible.builtin.get_url:
    url: "{{ minikube_repo }}"
    dest: "{{ minikube_path }}"
    mode: '0755'
  when: not minikube_existion.stat.exists
  become: true

- name: Check if kubectl exists
  ansible.builtin.stat:
    path: "{{ minikube_kubectl_path }}"
  register: kubectl_existion

- name: Install kubectl
  ansible.builtin.get_url:
    url: "{{ minikube_kubectl_repo }}"
    dest: "{{ minikube_kubectl_path }}"
    mode: '0755'
  when: not kubectl_existion.stat.exists
  become: true
