---
############################################################
### Logstash ###############################################

# Local service accounts
logstash_service_user: "logstash"
logstash_service_group: "logstash"
