---
#########################################################################################
### OPENSEARCH ##########################################################################

opensearch_service_port: 9200

opensearch_sysctl_vm_max_map_count: 262144

opensearch_server_tmp_dir: "/tmp/opensearch"

#########################################################################################
### FIREWALLD ###########################################################################

opensearch_firewalld_ports:
  - "{{ opensearch_service_port }}/tcp"
