---
name: ansible-lint
on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [minikube, redis, opensearch-stack]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ansible-lint
        id: lint
        uses: ansible/ansible-lint@main
        with:
          args: ${{ matrix.project }}/

  telegram-notify:
    runs-on: ubuntu-latest
    needs: ansible-lint
    if: always()
    steps:
      - name: Send telegram notification
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            üõ†Ô∏è Ansible Lint Status:
            Repository: [${{ github.repository }}](https://github.com/${{ github.repository }})
            Workflow: ${{ github.event.workflow_run.name || github.workflow }}
            Triggered by: [${{ github.actor }}](https://github.com/${{ github.actor }})
            Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Status: ${{ needs.ansible-lint.result }}
